[project]
name = "course-project-2-video-classification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "cOlterO", email = "43588141+cOlterO@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pandas>=3.0.6",
    "pillow>=12.3.0",
    "torch==2.11.0",
    "torchvision==0.26.0",
]

[project.scripts]
course-project-2-video-classification = "course_project_2_video_classification:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
torch = [
  { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
